### PR TITLE
Draft

### PR DESCRIPTION
**Pull request by sjsrey**
For discussion. Don't merge yet.

### CODE REVIEW

**Comment by darribas** [comment]
Is this good to merge @sjsrey?

**Comment by sjsrey** [comment]
Yes. I think we are also set on the install system as I tested it a bunch yesterday.

**Comment by sjsrey** [comment]
This can be merged. I will be doing some content editing on part 1, but this merge should take care of the installation infrastructure.

**Comment by sjsrey** [comment]
Closing as this is redundant

**Pull request closed without merging**
